services:
  - type: web
    name: hello-render-java
    env: java
    buildCommand: "mvn clean package"
    startCommand: "java -jar target/hello-render-java-1.0-SNAPSHOT-jar-with-dependencies.jar"
    envVars:
      - key: PORT
        value: 8080
